# Generated by Django 2.2.1 on 2019-08-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_genre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
