# Generated by Django 2.2.1 on 2019-08-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionapp', '0003_topic_topic_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_emot',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
