# Generated by Django 2.2.1 on 2019-08-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionapp', '0004_topic_topic_emot'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_negative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_positive',
            field=models.IntegerField(null=True),
        ),
    ]
